<?php

namespace app\modules\report\models;

use Yii;
use app\models\AdminUsers;

/**
 * This is the model class for table "pcci_reports_link".
 *
 * @property int $id
 * @property string $link
 * @property string $create_date
 * @property int $creator_id
 * @property int $reports_id
 *
 * @property AdminUsers $creator
 * @property PcciReports $reports
 */
class PcciReportsLink extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'pcci_reports_link';
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->create_date = date('d.m.Y', strtotime(str_replace("-", "", $this->create_date)));
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['link', 'creator_id', 'reports_id'], 'required'],
            [['create_date'], 'safe'],
            [['creator_id', 'reports_id'], 'default', 'value' => null],
            [['creator_id', 'reports_id'], 'integer'],
            [['link'], 'string', 'max' => 512],
            [['creator_id'], 'exist', 'skipOnError' => true, 'targetClass' => AdminUsers::className(), 'targetAttribute' => ['creator_id' => 'id']],
            [['reports_id'], 'exist', 'skipOnError' => true, 'targetClass' => PcciReports::className(), 'targetAttribute' => ['reports_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'link' => 'Link',
            'create_date' => 'Create Date',
            'creator_id' => 'Creator ID',
            'reports_id' => 'Reports ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreator()
    {
        return $this->hasOne(AdminUsers::className(), ['id' => 'creator_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReports()
    {
        return $this->hasOne(PcciReports::className(), ['id' => 'reports_id']);
    }
}
